### ISSUE TITLE
file limit tops at 76 - 79

### ISSUE THREAD

**Issue by Devicetron** [hassan-sd/civitai-image-scraper#2]
is it possible to remove this limit so get more images?

**Comment by CodeWithMa** [comment]
Hi there!
Thank you for raising this issue. After investigating the problem, I believe the behavior you're experiencing is related to the pagination mechanism used in the API.
By default, it fetches a maximum of 100 items per request.

To get the next page you can use this URL:
https://civitai.com/api/v1/images?page=2

**Comment by Devicetron** [comment]
where can I add the line to the civitai-image.py file?

**Comment by hassan-sd** [comment]
This should be fixed now, multiple new features added

- User input to set a min width/height of images to download
- User input for setting location to save
- User input to toggle NSFW only true or false
- Now the prompts saved have the <lora> removed so it's cleaner for training
- Pagination added to download more than one page of images
- Users can set the max amount of images/prompts to download
- Unicode saving
