### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by 2DOG-G** [hassan-sd/civitai-image-scraper#5]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\JOJO\Downloads\civitai-image-scraper-main\civitai-image.py", line 40, in <module>
    img.save(img_filename)
  File "D:\Software\python\Lib\site-packages\PIL\Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "D:\Software\python\Lib\site-packages\PIL\JpegImagePlugin.py", line 643, in _save    
    raise OSError(msg) from e
OSError: cannot write mode P as JPEG

**Comment by 2DOG-G** [comment]
I consulted CHATGPT to change line 42 of the code to

 img.save(img_filename,"PNG") 

But the maximum number of downloads is 100, is it because of API restrictions?

**Comment by 2DOG-G** [comment]
The number is limited in the API docs
The number of results to be returned per page. This can be a number between 0 and 200. By default, each page will return 100 results.

**Comment by 2DOG-G** [comment]
a solution,
Total >1000
Total >900
Total >800
run it several times, even
Total > 50 run once
Total > 49 run once

**Comment by hassan-sd** [comment]
This should be fixed now, multiple new features added

- User input to set a min width/height of images to download
- User input for setting location to save
- User input to toggle NSFW only true or false
- Now the prompts saved have the <lora> removed so it's cleaner for training
- Pagination added to download more than one page of images
- Users can set the max amount of images/prompts to download
- Unicode saving
